[tool.poetry]
name = "newsagent"
version = "0.1.0"
description = ""
authors = ["shrutisharma7500 <shrutisharma94827@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
